# packages below are almost copied from Ningrong's script
---

sys_packages:
  - build-essential
  - checkinstall
  - gcc
  - g++
  - make
  - python3
  - python3-pip
  - python3-setuptools
  - wget
  - curl
  - git
  - vim
  - tree
  - nload
  - screen
