# https://pre-commit.com/#install
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        files: \.(yml|yaml)$
        entry: ansible-lint
        language: python
        stages: [commit]
