---
- name: get all available shells
  command: cat /etc/shells
  register: valid_shells
  changed_when: false
  failed_when: false

- name: check if user_default_shell is available
  fail:
    msg: "{{ user_default_shell }} has not been installed yet"
  failed_when: not valid_shells.stdout.find(user_default_shell)
